### ISSUE TITLE
Step duplicates the build

### ISSUE THREAD

**Issue by benrnz-sv** [bitrise-steplib/steps-nunit-runner#10] opened 2016-11-10 21:27 UTC
Hi guys,
I've noticed that the NUnit-Runner step is always rebuilding the code inside the step.  This causes all my code to effectively build twice.  I'd prefer to run the unit tests against already built nunit projects output by the Builder step.

Is it possible to make this step more compose-able with other steps such that, you are required to have a Builder step beforehand for it to work?  For example the publish to Hockey step does not build the code inside its step, it requires the artefacts to already be built.

This would also reduce the maintenance work on this step to keep it in sync with changes to the Builder step.

Or at least can there be an option to build again if others are requiring this.

Thanks guys

**Comment by viktorbenei** [comment] 2016-11-10 23:31
@godrei please review

**Comment by godrei** [comment] 2016-12-06 11:56
Hi @benrnz-sv ,
the problem is, that for creating release version and for running tests most of the times you need to build the project with different configuration-platform combinations, thats why every xamarin steps are building the project.

For example: nunit-runner step needs an iPhoneSimulator build, but test-cloud needs iPhone build for releasing you probably need Release configuration, instead of debug.

**Comment by benrnz-sv** [comment] 2016-12-06 20:14
Thanks for the response.  
I understand the need for specific builds for specific purposes, but let me give you an example of why this would be useful for me.  
I have a separate build to run nightly UI Test automation in Xamarin Test Cloud.  This build first builds the solution using the Archive step, then runs all the unit tests.  The build configuration is actually iPhoneSimulator to be compatible with what TestCloud needs.  So, if I use the NUnit step this adds another minute to my build time.  Instead what I'm doing is using a Script step to manually run nunit so it doesn't do this. This is a little messy because it increases the amount of maintenance I need to do to maintain the script step and variables as compared to using the NUnit step.

Can it be an option you select if the build configuration is compatible?

**Comment by godrei** [comment] 2017-03-06 12:40
Closing as we did not receive a reply - @benrnz-sv please let us know if we can help with anything and we'll reopen this issue!

**Closed by godrei** 2017-03-06 12:40 UTC

**Comment by benrnz-sv** [comment] 2017-03-06 20:16
Apologies,I didn't see the notification of this until now.  Will do, I'll create a feature request.
Thanks.
